// Multi-Language Localization System for TravelBoost / YatraSetu

export type LanguageCode = 'en' | 'hi' | 'mr' | 'gu' | 'bn' | 'ta' | 'te' | 'es' | 'fr'

export interface LanguageOption {
  code: LanguageCode
  name: string
  nativeName: string
  flag: string
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
]

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    tagline: 'Plan Smarter. Explore Deeper. Travel Better.',
    aiPlanner: 'AI Travel Planner',
    localConnect: 'Local Connect',
    crowdPredictor: 'Crowd Predictor',
    cleanliness: 'Cleanliness',
    safety: 'Safety & SOS',
    community: 'Community & Gems',
    overview: 'Overview',
    signInWithGoogle: 'Sign In with Google',
    loginWithMobile: 'Login with Mobile & OTP',
    createAccount: 'Create New Account',
    chooseRole: 'Choose Your Role to Enter the Platform',
    touristRole: 'Tourist / Traveler',
    localRole: 'Local Host & Guide',
    authorityRole: 'Civic Authority',
    adminRole: 'System Admin',
    enterDestination: 'Select Destination',
    liveCrowd: 'Live Crowd Status',
    safeZone: 'Safe Zones & Police Kiosks',
    turnByTurn: 'Get Turn-by-Turn Directions & Traffic Status',
    startLocation: 'Starting Point / Current Location',
    destinationLocation: 'Destination Monument or Stay',
    getDirections: 'Show Route & Traffic on Map',
    trafficFast: 'Fast (Green)',
    trafficModerate: 'Moderate Delay (Amber)',
    trafficHeavy: 'Heavy Congestion (Red)',
  },
  hi: {
    tagline: 'समझदारी से योजना बनाएं। गहराई से खोजें। बेहतर यात्रा करें।',
    aiPlanner: 'एआई यात्रा योजनाकार',
    localConnect: 'स्थानीय संपर्क',
    crowdPredictor: 'भीड़ पूर्वानुमान',
    cleanliness: 'स्वच्छता रिपोर्ट',
    safety: 'सुरक्षा और आपातकालीन',
    community: 'समुदाय और गुप्त स्थल',
    overview: 'अवलोकन',
    signInWithGoogle: 'गूगल से लॉगिन करें',
    loginWithMobile: 'मोबाइल और ओटीपी से लॉगिन करें',
    createAccount: 'नया खाता बनाएं',
    chooseRole: 'मंच में प्रवेश करने के लिए अपनी भूमिका चुनें',
    touristRole: 'पर्यटक / यात्री',
    localRole: 'स्थानीय मेजबान और गाइड',
    authorityRole: 'नागरिक प्राधिकरण',
    adminRole: 'सिस्टम व्यवस्थापक',
    enterDestination: 'गंतव्य चुनें',
    liveCrowd: 'वर्तमान भीड़ स्थिति',
    safeZone: 'सुरक्षित क्षेत्र और पुलिस केंद्र',
    turnByTurn: 'मार्ग दिशानिर्देश और लाइव ट्रैफ़िक स्थिति प्राप्त करें',
    startLocation: 'प्रारंभिक स्थान / वर्तमान जीपीएस',
    destinationLocation: 'गंतव्य स्मारक या होमस्टे',
    getDirections: 'मानचित्र पर मार्ग और ट्रैफ़िक देखें',
    trafficFast: 'तेज प्रवाह (हरा)',
    trafficModerate: 'मध्यम ट्रैफ़िक (पीला)',
    trafficHeavy: 'भारी जाम (लाल)',
  },
  mr: {
    tagline: 'हुशारीने नियोजन करा. सखोल अनुभव घ्या. उत्तम प्रवास करा.',
    aiPlanner: 'एआय सहल नियोजक',
    localConnect: 'स्थानिक संपर्क',
    crowdPredictor: 'गर्दी अंदाज',
    cleanliness: 'स्वच्छता तक्रार',
    safety: 'सुरक्षा आणि आपत्कालीन मदत',
    community: 'समुदाय अनुभव',
    overview: 'मुख्य दृश्य',
    signInWithGoogle: 'गुगल ने लॉगिन करा',
    loginWithMobile: 'मोबाईल आणि ओटीपी द्वारे लॉगिन',
    createAccount: 'नवीन खाते तयार करा',
    chooseRole: 'तुमची भूमिका निवडा',
    touristRole: 'पर्यटक / प्रवासी',
    localRole: 'स्थानिक यजमान आणि मार्गदर्शक',
    authorityRole: 'नागरी प्राधिकरण',
    adminRole: 'प्रशासक',
    enterDestination: 'ठिकाण निवडा',
    liveCrowd: 'थेट गर्दीची स्थिती',
    safeZone: 'सुरक्षित क्षेत्र व पोलीस मदत कक्ष',
    turnByTurn: 'नकाशावर मार्ग आणि थेट रहदारीची माहिती पहा',
    startLocation: 'सुरुवातीचे ठिकाण',
    destinationLocation: 'गंतव्य स्थान',
    getDirections: 'दिशा व ट्रॅफिक दाखवा',
    trafficFast: 'वेगवान प्रवाह (हिरवा)',
    trafficModerate: 'मध्यम ट्रॅफिक (पिवळा)',
    trafficHeavy: 'जास्त गर्दी (लाल)',
  },
  gu: {
    tagline: 'સ્માર્ટ આયોજન કરો. ઊંડાણપૂર્વક શોધો. શ્રેષ્ઠ યાત્રા કરો.',
    aiPlanner: 'એઆઈ પ્રવાસ આયોજક',
    localConnect: 'સ્થાનિક કનેક્ટ',
    crowdPredictor: 'ભીડ અનુમાન',
    cleanliness: 'સ્વચ્છતા રિપોર્ટ',
    safety: 'સુરક્ષા અને સહાય',
    community: 'સમુદાય',
    overview: 'મુખ્ય પૃષ્ઠ',
    signInWithGoogle: 'ગૂગલથી સાઇન ઇન કરો',
    loginWithMobile: 'મોબાઇલ અને ઓટીપી લૉગિન',
    createAccount: 'નવું ખાતું બનાવો',
    chooseRole: 'તમારી ભૂમિકા પસંદ કરો',
    touristRole: 'પ્રવાસી',
    localRole: 'સ્થાનિક યજમાન અને ગાઇડ',
    authorityRole: 'નાગરિક સત્તામંડળ',
    adminRole: 'એડમિન',
    enterDestination: 'સ્થળ પસંદ કરો',
    liveCrowd: 'લાઈવ ભીડ સ્થિતિ',
    safeZone: 'સુરક્ષિત ક્ષેત્ર',
    turnByTurn: 'નકશા પર ટ્રાફિક અને રૂટ જુઓ',
    startLocation: 'શરૂઆતનું સ્થળ',
    destinationLocation: 'મુકામ સ્થળ',
    getDirections: 'દિશાઓ બતાવો',
    trafficFast: 'ઝડપી (લીલો)',
    trafficModerate: 'સામાન્ય ટ્રાફિક (પીળો)',
    trafficHeavy: 'ભારે ટ્રાફિક (લાલ)',
  },
  bn: {
    tagline: 'স্মার্ট পরিকল্পনা করুন। গভীরভাবে জানুন। চমৎকার ভ্রমণ করুন।',
    aiPlanner: 'এআই ট্রাভেল প্ল্যানার',
    localConnect: 'স্থানীয় সংযোগ',
    crowdPredictor: 'ভিড় পূর্বাভাস',
    cleanliness: 'পরিচ্ছন্নতা',
    safety: 'নিরাপত্তা ও জরুরি সেবা',
    community: 'কমিউনিটি',
    overview: 'একনজরে',
    signInWithGoogle: 'গুগল দিয়ে সাইন ইন করুন',
    loginWithMobile: 'মোবাইল ও ওটিপি দিয়ে লগইন',
    createAccount: 'নতুন অ্যাকাউন্ট তৈরি করুন',
    chooseRole: 'আপনার ভূমিকা নির্বাচন করুন',
    touristRole: 'পর্যটক / যাত্রী',
    localRole: 'স্থানীয় হোস্ট এবং গাইড',
    authorityRole: 'নাগরিক কর্তৃপক্ষ',
    adminRole: 'অ্যাডমিন',
    enterDestination: 'গন্তব্য নির্বাচন করুন',
    liveCrowd: 'লাইভ ভিড় পরিস্থিতি',
    safeZone: 'নিরাপদ অঞ্চল',
    turnByTurn: 'ম্যাপে রুট ও ট্রাফিক তথ্য দেখুন',
    startLocation: 'শুরুর স্থান',
    destinationLocation: 'গন্তব্য স্থান',
    getDirections: 'পথ নির্দেশিকা দেখুন',
    trafficFast: 'স্বাভাবিক (সবুজ)',
    trafficModerate: 'মাঝারি জ্যাম (হলুদ)',
    trafficHeavy: 'তীব্র যানজট (লাল)',
  },
  ta: {
    tagline: 'புத்திசாலித்தனமாக திட்டமிடுங்கள். ஆழமாக ஆராயுங்கள். சிறப்பாக பயணம் செய்யுங்கள்.',
    aiPlanner: 'ஏஐ பயணத் திட்டம்',
    localConnect: 'உள்ளூர் இணைப்பு',
    crowdPredictor: 'கூட்ட முன்னறிவிப்பு',
    cleanliness: 'தூய்மை அறிக்கை',
    safety: 'பாதுகாப்பு & அவசர உதவி',
    community: 'சமூகம்',
    overview: 'மேலோட்டம்',
    signInWithGoogle: 'Google மூலம் உள்நுழைக',
    loginWithMobile: 'மொபைல் & OTP மூலம் உள்நுழைக',
    createAccount: 'புதிய கணக்கை உருவாக்கவும்',
    chooseRole: 'உங்கள் பாத்திரத்தைத் தேர்வுசெய்க',
    touristRole: 'பயணி',
    localRole: 'உள்ளூர் வழிகாட்டி',
    authorityRole: 'அதிகார சபை',
    adminRole: 'நிர்வாகி',
    enterDestination: 'இடத்தை தேர்வு செய்க',
    liveCrowd: 'நேரலை கூட்ட நிலை',
    safeZone: 'பாதுகாப்பான மண்டலம்',
    turnByTurn: 'வரைபடத்தில் வழி மற்றும் போக்குவரத்து நிலை',
    startLocation: 'தொடக்க இடம்',
    destinationLocation: 'சேருமிடம்',
    getDirections: 'வழியைப் பார்க்கவும்',
    trafficFast: 'விரைவான (பச்சை)',
    trafficModerate: 'மிதமான போக்குவரத்து (மஞ்சள்)',
    trafficHeavy: 'அதிக போக்குவரத்து (சிகப்பு)',
  },
  te: {
    tagline: 'తెలివిగా ప్లాన్ చేయండి. లోతుగా అన్వేషించండి. మెరుగ్గా ప్రయాణించండి.',
    aiPlanner: 'AI ట్రావెల్ ప్లానర్',
    localConnect: 'స్థానిక అనుసంధానం',
    crowdPredictor: 'రద్దీ అంచనా',
    cleanliness: 'పరిశుభ్రత నివేదిక',
    safety: 'భద్రత & అత్యవసర సేవలు',
    community: 'సముదాయం',
    overview: 'అవలోకనం',
    signInWithGoogle: 'Google తో లాగిన్ అవ్వండి',
    loginWithMobile: 'మొబైల్ & OTP తో లాగిన్',
    createAccount: 'కొత్త ఖాతాను సృష్టించండి',
    chooseRole: 'మీ పాత్రను ఎంచుకోండి',
    touristRole: 'పర్యాటకుడు',
    localRole: 'స్థానిక హోస్ట్ మరియు గైడ్',
    authorityRole: 'అధికార యంత్రాంగం',
    adminRole: 'అడ్మిన్',
    enterDestination: 'గమ్యాన్ని ఎంచుకోండి',
    liveCrowd: 'లైవ్ రద్దీ స్థితి',
    safeZone: 'సురక్షిత ప్రాంతం',
    turnByTurn: 'మ్యాప్‌లో రూట్ మరియు ట్రాఫిక్ చూడండి',
    startLocation: 'ప్రారంభ స్థానం',
    destinationLocation: 'గమ్యస్థానం',
    getDirections: 'రూట్ చూపించు',
    trafficFast: 'వేగవంతమైన ప్రవాహం (ఆకుపచ్చ)',
    trafficModerate: 'మధ్యస్థ ట్రాఫిక్ (పసుపు)',
    trafficHeavy: 'భారీ ట్రాఫిక్ (ఎరుపు)',
  },
  es: {
    tagline: 'Planifica mejor. Explora más profundo. Viaja mejor.',
    aiPlanner: 'Planificador IA',
    localConnect: 'Conexión Local',
    crowdPredictor: 'Predictor de Multitudes',
    cleanliness: 'Limpieza Cívica',
    safety: 'Seguridad y SOS',
    community: 'Comunidad',
    overview: 'Inicio',
    signInWithGoogle: 'Iniciar sesión con Google',
    loginWithMobile: 'Acceder con Móvil y OTP',
    createAccount: 'Crear cuenta nueva',
    chooseRole: 'Elige tu rol',
    touristRole: 'Turista / Viajero',
    localRole: 'Anfitrión y Guía Local',
    authorityRole: 'Autoridad Cívica',
    adminRole: 'Administrador',
    enterDestination: 'Seleccionar Destino',
    liveCrowd: 'Estado de Multitud en Vivo',
    safeZone: 'Zonas Seguras y Policía',
    turnByTurn: 'Ruta Paso a Paso y Estado de Tráfico',
    startLocation: 'Punto de partida',
    destinationLocation: 'Destino',
    getDirections: 'Mostrar Ruta y Tráfico',
    trafficFast: 'Tráfico fluido (Verde)',
    trafficModerate: 'Tráfico moderado (Ámbar)',
    trafficHeavy: 'Tráfico pesado (Rojo)',
  },
  fr: {
    tagline: 'Planifiez plus intelligemment. Explorez plus profondément. Voyagez mieux.',
    aiPlanner: 'Planificateur IA',
    localConnect: 'Connexion Locale',
    crowdPredictor: 'Prévision d’affluence',
    cleanliness: 'Propreté Civique',
    safety: 'Sécurité & SOS',
    community: 'Communauté',
    overview: 'Aperçu',
    signInWithGoogle: 'Se connecter avec Google',
    loginWithMobile: 'Connexion Mobile & OTP',
    createAccount: 'Créer un nouveau compte',
    chooseRole: 'Choisissez votre rôle',
    touristRole: 'Touriste / Voyageur',
    localRole: 'Hôte et Guide Local',
    authorityRole: 'Autorité Municipale',
    adminRole: 'Administrateur',
    enterDestination: 'Sélectionner une destination',
    liveCrowd: 'Affluence en direct',
    safeZone: 'Zones sécurisées & Police',
    turnByTurn: 'Itinéraire et état du trafic',
    startLocation: 'Point de départ',
    destinationLocation: 'Lieu de destination',
    getDirections: 'Afficher l’itinéraire et le trafic',
    trafficFast: 'Fluide (Vert)',
    trafficModerate: 'Ralentissement (Orange)',
    trafficHeavy: 'Embouteillage (Rouge)',
  },
}

const LANG_STORAGE_KEY = 'travelboost_selected_lang'

export function getSavedLanguage(): LanguageCode {
  try {
    const saved = localStorage.getItem(LANG_STORAGE_KEY) as LanguageCode
    if (saved && TRANSLATIONS[saved]) return saved
  } catch {}
  return 'en'
}

export function saveLanguage(code: LanguageCode) {
  try {
    localStorage.setItem(LANG_STORAGE_KEY, code)
  } catch {}
}
